apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  creationTimestamp: "2024-01-27T21:29:34Z"
  generation: 1
  labels:
    kwasm.sh/job: "true"
  name: wasmtime-spin-v2-provisioner
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Node
    name: kind-control-plane
    uid: 16f99ef3-ac14-4517-ac4d-25da238b2172
  resourceVersion: "667"
  uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
        batch.kubernetes.io/job-name: wasmtime-spin-v2-provisioner
        controller-uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
        job-name: wasmtime-spin-v2-provisioner
    spec:
      containers:
      - env:
        - name: NODE_ROOT
          value: /mnt/node-root
        - name: SHIM_LOCATION
          value: https://github.com/deislabs/containerd-wasm-shims/releases/download/v0.10.0/containerd-wasm-shims-v2-spin-linux-aarch64.tar.gz
        - name: SHIM_FETCH_STRATEGY
          value: /mnt/node-root
        image: voigt/kwasm-node-installer:new
        imagePullPolicy: IfNotPresent
        name: kwasm-provision
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/node-root
          name: root-mount
      dnsPolicy: ClusterFirst
      hostPID: true
      nodeName: wasmtime-spin-v2
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: ""
        name: root-mount
status:
  active: 1
  failed: 2
  ready: 0
  startTime: "2024-01-27T21:29:34Z"
  uncountedTerminatedPods: {}
