apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-27T21:30:43Z"
  finalizers:
  - batch.kubernetes.io/job-tracking
  generateName: wasmtime-spin-v2-provisioner-
  labels:
    batch.kubernetes.io/controller-uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
    batch.kubernetes.io/job-name: wasmtime-spin-v2-provisioner
    controller-uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
    job-name: wasmtime-spin-v2-provisioner
  name: wasmtime-spin-v2-provisioner-8mz2r
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: wasmtime-spin-v2-provisioner
    uid: 6ae1debc-e68f-4f76-a589-38065c01ce88
  resourceVersion: "592"
  uid: 1e325f9c-806e-4983-9a8d-bdc73b62b6ce
spec:
  containers:
  - env:
    - name: NODE_ROOT
      value: /mnt/node-root
    - name: SHIM_LOCATION
      value: https://github.com/deislabs/containerd-wasm-shims/releases/download/v0.10.0/containerd-wasm-shims-v2-spin-linux-aarch64.tar.gz
    - name: SHIM_FETCH_STRATEGY
      value: /mnt/node-root
    image: voigt/kwasm-node-installer:new
    imagePullPolicy: IfNotPresent
    name: kwasm-provision
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/node-root
      name: root-mount
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x4twh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostPID: true
  nodeName: wasmtime-spin-v2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /
      type: ""
    name: root-mount
  - name: kube-api-access-x4twh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  phase: Pending
  qosClass: BestEffort
