apiVersion: runtime.kwasm.sh/v1beta1 
kind: Shim
metadata:
  name: my-shim-v0.1.2
spec:
  nodeSelector:
    wasm: "true"

  fetchStrategy:
    type: annonymousHttp
    anonHttp:
      location: https://github.com/some-org/some-project/releases/v0.8.0/shims.tar.gz

  runtimeClass:
    name: my-shim-v0.1.2

  rolloutStrategy:
    type: rolling
    rolling:
      maxUpdate: 5 # 