apiVersion: runtime.kwasm.sh/v1alpha1 
kind: Shim
metadata:
  name: slight-v1
spec:
  nodeSelector:
    slight: "true"

  fetchStrategy:
    type: annonymousHttp
    anonHttp:
      location: "https://github.com/deislabs/containerd-wasm-shims/releases/download/v0.10.0/containerd-wasm-shims-v1-slight-linux-aarch64.tar.gz"

  runtimeClass:
    name: slight-v1
    handler: slight

  rolloutStrategy:
    type: recreate
