apiVersion: runtime.kwasm.sh/v1alpha1 
kind: Shim
metadata:
  name: wws-v1
  labels:
    app.kubernetes.io/name: wws-v1
    app.kubernetes.io/instance: wws-v1
    app.kubernetes.io/part-of: kwasm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kwasm-operator
spec:
  nodeSelector:
    wws: "true"

  fetchStrategy:
    type: annonymousHttp
    anonHttp:
      location: "https://github.com/deislabs/containerd-wasm-shims/releases/download/v0.10.0/containerd-wasm-shims-v1-wws-linux-aarch64.tar.gz"

  runtimeClass:
    name: wws-v1
    handler: wws

  rolloutStrategy:
    type: recreate
